version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - bot/.env

  bank:
    build:
      context: .
      dockerfile: bank/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - bank/.env

  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"